#!/usr/bin/env bash
# block-iocs.sh
# Block C2 / IOC domains and IPs on Linux and macOS.
#
# Usage:
#   sudo ./block-iocs.sh                 # block (default)
#   sudo ./block-iocs.sh --unblock       # remove all entries this script added
#   sudo ./block-iocs.sh --dry-run       # show what would be done, change nothing
#   sudo ./block-iocs.sh --hosts-only    # skip firewall, only modify /etc/hosts
#   sudo ./block-iocs.sh --no-firewall   # alias for --hosts-only
#   sudo ./block-iocs.sh --iocs ./iocs.txt   # use a different IOC file
#
# Requirements:
#   - bash 4+
#   - root (for editing /etc/hosts and adding firewall rules)
#   - One of: iptables, nft, ufw (Linux); pfctl (macOS). Optional.
#
# Behavior:
#   - Backs up /etc/hosts to /etc/hosts.bak.<timestamp> on first run.
#   - Adds entries between BEGIN/END markers so --unblock can cleanly remove them.
#   - On Linux, prefers nft > iptables > ufw, in that order. Falls back to nothing
#     with a warning if none are available.
#   - On macOS, uses pf (pfctl) with an anchor file in /etc/pf.anchors/.
#
# This script is idempotent: re-running it will not duplicate entries.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
IOC_FILE_DEFAULT="${SCRIPT_DIR}/iocs.txt"
IOC_FILE="$IOC_FILE_DEFAULT"
HOSTS_FILE="/etc/hosts"
MARKER_BEGIN="# === BEGIN polinrider IOC block ==="
MARKER_END="# === END polinrider IOC block ==="
PF_ANCHOR_NAME="polinrider_iocs"
PF_ANCHOR_FILE="/etc/pf.anchors/${PF_ANCHOR_NAME}"

ACTION="block"
DRY_RUN=0
HOSTS_ONLY=0

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------
while [[ $# -gt 0 ]]; do
  case "$1" in
    --unblock)        ACTION="unblock"; shift ;;
    --dry-run)        DRY_RUN=1; shift ;;
    --hosts-only|--no-firewall) HOSTS_ONLY=1; shift ;;
    --iocs)           IOC_FILE="$2"; shift 2 ;;
    -h|--help)
      grep -E '^#( |$)' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 2
      ;;
  esac
done

# ---------------------------------------------------------------------------
# Logging helpers
# ---------------------------------------------------------------------------
log()  { printf '\033[1;34m[*]\033[0m %s\n' "$*"; }
ok()   { printf '\033[1;32m[+]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[!]\033[0m %s\n' "$*" >&2; }
err()  { printf '\033[1;31m[X]\033[0m %s\n' "$*" >&2; }
do_or_dry() {
  if [[ $DRY_RUN -eq 1 ]]; then
    printf '\033[1;36m[dry]\033[0m %s\n' "$*"
  else
    eval "$@"
  fi
}

# ---------------------------------------------------------------------------
# Pre-flight
# ---------------------------------------------------------------------------
if [[ ! -f "$IOC_FILE" ]]; then
  err "IOC file not found: $IOC_FILE"
  exit 1
fi

OS_NAME="$(uname -s)"
if [[ "$OS_NAME" != "Linux" && "$OS_NAME" != "Darwin" ]]; then
  err "Unsupported OS: $OS_NAME"
  exit 1
fi

if [[ $EUID -ne 0 && $DRY_RUN -ne 1 ]]; then
  err "This script must be run as root (or with sudo)."
  exit 1
fi

# ---------------------------------------------------------------------------
# Parse IOC file: split into domains and IPs
# ---------------------------------------------------------------------------
DOMAINS=()
IPS=()

is_ipv4() { [[ "$1" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; }
is_ipv6() { [[ "$1" =~ : ]] && [[ "$1" =~ ^[0-9A-Fa-f:]+$ ]]; }
is_ip()   { is_ipv4 "$1" || is_ipv6 "$1"; }

while IFS= read -r line || [[ -n "$line" ]]; do
  # Strip trailing comments
  raw="${line%%#*}"
  # Trim whitespace
  raw="$(echo "$raw" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')"
  [[ -z "$raw" ]] && continue
  if is_ip "$raw"; then
    IPS+=("$raw")
  else
    DOMAINS+=("$raw")
  fi
done < "$IOC_FILE"

log "Loaded ${#DOMAINS[@]} domains and ${#IPS[@]} IPs from $IOC_FILE"

# ---------------------------------------------------------------------------
# /etc/hosts edits
# ---------------------------------------------------------------------------
backup_hosts() {
  local ts
  ts="$(date +%Y%m%d-%H%M%S)"
  do_or_dry "cp -p '$HOSTS_FILE' '${HOSTS_FILE}.bak.${ts}'"
  ok "Backed up $HOSTS_FILE to ${HOSTS_FILE}.bak.${ts}"
}

remove_hosts_block() {
  if grep -qF "$MARKER_BEGIN" "$HOSTS_FILE" 2>/dev/null; then
    do_or_dry "sed -i.tmp '/${MARKER_BEGIN}/,/${MARKER_END}/d' '$HOSTS_FILE' && rm -f '${HOSTS_FILE}.tmp'"
    ok "Removed existing IOC block from $HOSTS_FILE"
  fi
}

write_hosts_block() {
  if [[ ${#DOMAINS[@]} -eq 0 ]]; then
    log "No domains to block in $HOSTS_FILE"
    return
  fi
  {
    echo ""
    echo "$MARKER_BEGIN"
    echo "# Generated by block-iocs.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# Source: $IOC_FILE"
    for d in "${DOMAINS[@]}"; do
      printf '0.0.0.0 %s\n' "$d"
      printf ':: %s\n' "$d"
    done
    echo "$MARKER_END"
  } > /tmp/.polinrider-hosts-block.$$

  if [[ $DRY_RUN -eq 1 ]]; then
    printf '\033[1;36m[dry]\033[0m would append to %s:\n' "$HOSTS_FILE"
    cat /tmp/.polinrider-hosts-block.$$
    rm -f /tmp/.polinrider-hosts-block.$$
  else
    cat /tmp/.polinrider-hosts-block.$$ >> "$HOSTS_FILE"
    rm -f /tmp/.polinrider-hosts-block.$$
    ok "Wrote ${#DOMAINS[@]} domains to $HOSTS_FILE"
  fi
}

# ---------------------------------------------------------------------------
# Linux firewall — try nft, iptables, then ufw
# ---------------------------------------------------------------------------
linux_block_ips() {
  [[ ${#IPS[@]} -eq 0 ]] && { log "No IPs to block via firewall"; return; }

  if command -v nft &>/dev/null; then
    log "Using nftables to block ${#IPS[@]} IPs"
    do_or_dry "nft add table inet polinrider 2>/dev/null || true"
    do_or_dry "nft add set inet polinrider iocs '{ type ipv4_addr; flags interval; }' 2>/dev/null || true"
    do_or_dry "nft add set inet polinrider iocs6 '{ type ipv6_addr; flags interval; }' 2>/dev/null || true"
    do_or_dry "nft add chain inet polinrider out '{ type filter hook output priority 0; }' 2>/dev/null || true"
    do_or_dry "nft add rule inet polinrider out ip daddr @iocs counter drop 2>/dev/null || true"
    do_or_dry "nft add rule inet polinrider out ip6 daddr @iocs6 counter drop 2>/dev/null || true"
    for ip in "${IPS[@]}"; do
      if is_ipv4 "$ip"; then
        do_or_dry "nft add element inet polinrider iocs '{ $ip }' 2>/dev/null || true"
      else
        do_or_dry "nft add element inet polinrider iocs6 '{ $ip }' 2>/dev/null || true"
      fi
    done
    ok "nftables rules applied"
  elif command -v iptables &>/dev/null; then
    log "Using iptables to block ${#IPS[@]} IPs"
    for ip in "${IPS[@]}"; do
      if is_ipv4 "$ip"; then
        do_or_dry "iptables -C OUTPUT -d '$ip' -j DROP -m comment --comment 'polinrider' 2>/dev/null || iptables -A OUTPUT -d '$ip' -j DROP -m comment --comment 'polinrider'"
      elif command -v ip6tables &>/dev/null; then
        do_or_dry "ip6tables -C OUTPUT -d '$ip' -j DROP -m comment --comment 'polinrider' 2>/dev/null || ip6tables -A OUTPUT -d '$ip' -j DROP -m comment --comment 'polinrider'"
      fi
    done
    ok "iptables rules applied (note: not persisted across reboots — see iptables-persistent)"
  elif command -v ufw &>/dev/null; then
    log "Using ufw to block ${#IPS[@]} IPs"
    for ip in "${IPS[@]}"; do
      do_or_dry "ufw deny out to '$ip' comment 'polinrider' 2>/dev/null || true"
    done
    ok "ufw rules applied"
  else
    warn "No supported firewall tool found (nft, iptables, ufw). IP-level blocking skipped."
  fi
}

linux_unblock_ips() {
  if command -v nft &>/dev/null; then
    do_or_dry "nft delete table inet polinrider 2>/dev/null || true"
    ok "nftables polinrider table removed"
  fi
  if command -v iptables &>/dev/null; then
    while iptables -S OUTPUT | grep -q -- '--comment "polinrider"'; do
      rule=$(iptables -S OUTPUT | grep -m1 -- '--comment "polinrider"')
      do_or_dry "iptables ${rule/-A/-D}"
    done
    ok "iptables polinrider rules removed"
  fi
  if command -v ip6tables &>/dev/null; then
    while ip6tables -S OUTPUT | grep -q -- '--comment "polinrider"'; do
      rule=$(ip6tables -S OUTPUT | grep -m1 -- '--comment "polinrider"')
      do_or_dry "ip6tables ${rule/-A/-D}"
    done
  fi
  if command -v ufw &>/dev/null; then
    do_or_dry "ufw status numbered | grep polinrider | awk '{print \$1}' | tr -d '[]' | sort -rn | xargs -I{} ufw --force delete {} 2>/dev/null || true"
  fi
}

# ---------------------------------------------------------------------------
# macOS firewall — pfctl with an anchor
# ---------------------------------------------------------------------------
macos_block_ips() {
  [[ ${#IPS[@]} -eq 0 ]] && { log "No IPs to block via firewall"; return; }
  log "Using pf to block ${#IPS[@]} IPs (anchor: $PF_ANCHOR_NAME)"

  # Build anchor file
  {
    echo "# polinrider IOC block — generated $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    for ip in "${IPS[@]}"; do
      printf 'block drop quick from any to %s\n' "$ip"
    done
  } > /tmp/.polinrider-pf.$$

  if [[ $DRY_RUN -eq 1 ]]; then
    printf '\033[1;36m[dry]\033[0m would write %s:\n' "$PF_ANCHOR_FILE"
    cat /tmp/.polinrider-pf.$$
    rm -f /tmp/.polinrider-pf.$$
    return
  fi

  install -m 0644 /tmp/.polinrider-pf.$$ "$PF_ANCHOR_FILE"
  rm -f /tmp/.polinrider-pf.$$

  # Reference the anchor from /etc/pf.conf if not already
  if ! grep -qF "anchor \"$PF_ANCHOR_NAME\"" /etc/pf.conf; then
    {
      echo ""
      echo "# polinrider"
      echo "anchor \"$PF_ANCHOR_NAME\""
      echo "load anchor \"$PF_ANCHOR_NAME\" from \"$PF_ANCHOR_FILE\""
    } >> /etc/pf.conf
    ok "Added anchor reference to /etc/pf.conf"
  fi

  pfctl -ef /etc/pf.conf 2>/dev/null || true
  pfctl -a "$PF_ANCHOR_NAME" -f "$PF_ANCHOR_FILE"
  ok "pf anchor loaded with ${#IPS[@]} block rules"
}

macos_unblock_ips() {
  if [[ -f "$PF_ANCHOR_FILE" ]]; then
    do_or_dry "pfctl -a '$PF_ANCHOR_NAME' -F all 2>/dev/null || true"
    do_or_dry "rm -f '$PF_ANCHOR_FILE'"
    ok "Removed pf anchor file"
  fi
  if grep -qF "anchor \"$PF_ANCHOR_NAME\"" /etc/pf.conf 2>/dev/null; then
    do_or_dry "sed -i.bak '/polinrider/d; /anchor \"$PF_ANCHOR_NAME\"/d; /load anchor \"$PF_ANCHOR_NAME\"/d' /etc/pf.conf"
    ok "Removed anchor reference from /etc/pf.conf"
  fi
  do_or_dry "pfctl -f /etc/pf.conf 2>/dev/null || true"
}

# ---------------------------------------------------------------------------
# DNS cache flush (best-effort)
# ---------------------------------------------------------------------------
flush_dns() {
  case "$OS_NAME" in
    Darwin)
      do_or_dry "dscacheutil -flushcache 2>/dev/null || true"
      do_or_dry "killall -HUP mDNSResponder 2>/dev/null || true"
      ok "macOS DNS cache flushed"
      ;;
    Linux)
      if command -v resolvectl &>/dev/null; then
        do_or_dry "resolvectl flush-caches 2>/dev/null || true"
        ok "systemd-resolved cache flushed"
      elif command -v systemd-resolve &>/dev/null; then
        do_or_dry "systemd-resolve --flush-caches 2>/dev/null || true"
        ok "systemd-resolve cache flushed"
      else
        warn "No DNS cache flush tool found; restart your resolver if needed"
      fi
      ;;
  esac
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
log "Action: $ACTION  (OS: $OS_NAME, dry-run: $DRY_RUN)"

if [[ "$ACTION" == "block" ]]; then
  backup_hosts
  remove_hosts_block      # remove old block before writing new (idempotency)
  write_hosts_block

  if [[ $HOSTS_ONLY -eq 0 ]]; then
    case "$OS_NAME" in
      Linux)  linux_block_ips ;;
      Darwin) macos_block_ips ;;
    esac
  fi

  flush_dns
  ok "Block complete. Verify with:  dig +short ${DOMAINS[0]:-api.trongrid.io}"
elif [[ "$ACTION" == "unblock" ]]; then
  remove_hosts_block

  if [[ $HOSTS_ONLY -eq 0 ]]; then
    case "$OS_NAME" in
      Linux)  linux_unblock_ips ;;
      Darwin) macos_unblock_ips ;;
    esac
  fi

  flush_dns
  ok "Unblock complete."
fi
